### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by 461353349** [GeneralElectric/CalculiX#1]
@GeneralElectric
When I runned command "build.sh 2.10 2.10", An compilation error happened as followings:

Installing ...
cp: cannot stat '/mingw/calculixsrc/x64/build/CalculiX/cgx_2.10/src/cgx':No such file or directory
Adding build information ...
Unix2Dos: Processing file buildInfo.log

I tried to change the content in 262th row
    cp -p $BUILD_DIR/CalculiX/cgx_$CGX_VERSION/src/cgx.exe cgx.exe
 as the following 
    cp -p $BUILD_DIR/CalculiX/cgx_$CGX_VERSION/src/cgx cgx.exe
The error is the same. 

So can you help me?

**Comment by guardino** [comment]
This could indicate there was an issue compiling cgx.exe or one of its dependencies on your system. Please check the build logs - they are located in the x64/output directory. The actual builds occur in x64/build. Also ensure you've setup the shell environment as described in:
https://github.com/GeneralElectric/CalculiX/blob/master/src/doc/BuildInstructions.txt

**Comment by 461353349** [comment]
@guardino
Thanks a lot.
When I change x86_64-6.2.0-win32-seh-rt_v5-rev1 as x86_64-4.8.2-release-win32-seh-rt_v3-rev3, Compilation is OK.
Error happened in the file "stl_algo.h" when using mingw6.2.0.

**Comment by guardino** [comment]
Thanks for the useful feedback and for letting me know you can now compile the code using MinGW-x64 4.8.2.
