### ISSUE TITLE
CCX 2.11 sources?

### ISSUE THREAD

**Issue by luzpaz** [GeneralElectric/CalculiX#2]
will this repo get updated soon?

**Comment by luzpaz** [comment]
how does one submit patches to ccx (not necessarily just the windows port)?

**Comment by luzpaz** [comment]
CC @guardino

**Comment by guardino** [comment]
I have no immediate plans to update this repository, but I am waiting to see what features will be available in the next CalculiX version. If you have specific requirements or questions, feel free to let me know. For submitting patches, please contact the main CalculiX developers.
